version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
steps:
  - run:
      name: Install libs
      command: sudo apt-get install libxtst6 libgconf-2-4 libnss3 libasound2 libgtk-3-0 libxss1
  - run: npm install
  - run: npm run e2e
   
 
